/**
 * Default templates. Seeded into NotificationTemplate, where the Super Admin can edit them.
 * Variables use {{name}}. SMS text starts with "ANU:" and never contains grades or marks.
 */
export interface TemplateDefinition {
  eventKey: string;
  emailSubject: string;
  emailBody: string;
  smsBody: string;
  inAppTitle: string;
  inAppBody: string;
}

export const EVENT_KEYS = {
  STUDENT_ACCOUNT_CREATED: 'student.account_created',
  STAFF_ACCOUNT_CREATED: 'staff.account_created',
  STAFF_ROLES_UPDATED: 'staff.roles_updated',
  TEACHING_ASSIGNED: 'teaching.assigned',
  REGISTRATION_APPROVED: 'registration.approved',
  REGISTRATION_REJECTED: 'registration.rejected',
  RESULTS_AWAITING_APPROVAL: 'results.awaiting_approval',
  RESULTS_RETURNED: 'results.returned',
  ATTENDANCE_LOW: 'attendance.low',
  DEVOTION_FINAL: 'devotion.final',
  PARTNER_ACCOUNT_CREATED: 'partner.account_created',
  HOSTEL_OFFERED: 'accommodation.offered',
  HOSTEL_UNPLACED: 'accommodation.unplaced',
  HOSTEL_OFFER_EXPIRED: 'accommodation.offer_expired',
  HOSTEL_ALLOCATION_CHANGED: 'accommodation.allocation_changed',
  PRIVATE_BOOKING_REQUESTED: 'private_booking.requested',
  PRIVATE_BOOKING_RESPONDED: 'private_booking.responded',
  PRIVATE_BOOKING_CANCELLED: 'private_booking.cancelled',
  HOSTEL_VERIFICATION: 'private_hostel.verification',
  LIBRARY_DUE_SOON: 'library.due_soon',
  LIBRARY_OVERDUE: 'library.overdue',
  LIBRARY_HOLD_READY: 'library.hold_ready',
  LIBRARY_HOLD_EXPIRED: 'library.hold_expired',
  LIBRARY_FINE: 'library.fine',
  FOOD_ORDER_NEW: 'food.order_new',
  FOOD_ORDER_UPDATE: 'food.order_update',
  VENDOR_REVIEW: 'vendor.review',
  RESULTS_PUBLISHED: 'results.published',
  INTERNALS_UPDATED: 'internals.updated',
  EXAM_TIMETABLE_PUBLISHED: 'exam_timetable.published',
  EXAM_ELIGIBILITY_PUBLISHED: 'exam_eligibility.published',
  ACCOUNT_LOCKED: 'security.account_locked',
  PASSWORD_RESET_CODE: 'security.password_reset_code',
  PASSWORD_CHANGED: 'security.password_changed',
  DEVELOPER_ACCESS_CHANGED: 'security.developer_access_changed',
} as const;

export const DEFAULT_TEMPLATES: TemplateDefinition[] = [
  {
    eventKey: EVENT_KEYS.STUDENT_ACCOUNT_CREATED,
    emailSubject: 'Set up your All Nations University student account',
    emailBody:
      'Dear {{firstName}},\n\nWelcome to All Nations University. Your student account has been created.\n\nIndex number: {{indexNumber}}\n\nChoose your password using this link. It works once and expires in {{expiresHours}} hours:\n{{setupUrl}}\n\nAfterwards, sign in at {{portalUrl}}/login with your index number and the password you chose.\n\nIf you did not expect this email, contact the Registry.\n\nAcademic Affairs\nAll Nations University',
    smsBody: 'ANU: Your student account is ready. Index number: {{indexNumber}}. Check {{email}} for the link to set your password.',
    inAppTitle: 'Welcome to All Nations University',
    inAppBody: 'Your student account is set up.',
  },
  {
    eventKey: EVENT_KEYS.STAFF_ACCOUNT_CREATED,
    emailSubject: 'Set up your All Nations University staff account',
    emailBody:
      'Dear {{firstName}},\n\nA staff account has been created for you on the ANU platform.\n\nSign-in email: {{email}}\nRoles: {{roles}}\n\nChoose your password using this link. It works once and expires in {{expiresHours}} hours:\n{{setupUrl}}\n\nThen sign in at {{portalUrl}}/staff/login. On your first sign-in you will set up an authenticator app on your phone, which staff accounts require.\n\nAll Nations University',
    smsBody: 'ANU: Your staff account is ready. Check {{email}} for the link to set your password.',
    inAppTitle: 'Welcome',
    inAppBody: 'Your staff account is set up.',
  },
  {
    eventKey: EVENT_KEYS.STAFF_ROLES_UPDATED,
    emailSubject: 'Your roles on the ANU platform changed',
    emailBody: 'Dear {{firstName}},\n\nYour roles were updated by {{actor}}.\n\nYour roles now: {{roles}}\n\nSign out and back in if a menu you expect is missing. Contact ICT if this change looks wrong.\n\nAll Nations University',
    smsBody: 'ANU: Your platform roles were updated. Check your email for details.',
    inAppTitle: 'Your roles changed',
    inAppBody: 'You now hold: {{roles}}.',
  },
  {
    eventKey: EVENT_KEYS.TEACHING_ASSIGNED,
    emailSubject: 'You are teaching {{courseCode}} in {{semesterLabel}}',
    emailBody: 'Dear {{firstName}},\n\nYou have been assigned to teach {{courseCode}} {{courseTitle}} in {{semesterLabel}}{{leadNote}}.\n\nYour class list is under My classes at {{portalUrl}}/teaching once students are approved.\n\nAll Nations University',
    smsBody: 'ANU: You are assigned to teach {{courseCode}} in {{semesterLabel}}.',
    inAppTitle: 'New teaching assignment',
    inAppBody: '{{courseCode}} {{courseTitle}}, {{semesterLabel}}{{leadNote}}.',
  },
  {
    eventKey: EVENT_KEYS.REGISTRATION_APPROVED,
    emailSubject: 'Course registration approved: {{semesterLabel}}',
    emailBody: 'Dear {{firstName}},\n\nYour course registration for {{semesterLabel}} has been approved ({{courseCount}} courses, {{credits}} credits).\n{{noteLine}}\nView it at {{portalUrl}}/registration\n\nAll Nations University',
    smsBody: 'ANU: Your course registration for {{semesterLabel}} is approved ({{courseCount}} courses, {{credits}} credits).',
    inAppTitle: 'Course registration approved',
    inAppBody: '{{semesterLabel}}: {{courseCount}} courses, {{credits}} credits. {{noteLine}}',
  },
  {
    eventKey: EVENT_KEYS.REGISTRATION_REJECTED,
    emailSubject: 'Course registration needs changes: {{semesterLabel}}',
    emailBody: 'Dear {{firstName}},\n\nYour course registration for {{semesterLabel}} was returned for changes.\n\nReason: {{note}}\n\nUpdate and resubmit it at {{portalUrl}}/registration before registration closes on {{closesAt}}.\n\nAll Nations University',
    smsBody: 'ANU: Your course registration for {{semesterLabel}} needs changes. Sign in to see why and resubmit before {{closesAt}}.',
    inAppTitle: 'Course registration needs changes',
    inAppBody: 'Reason: {{note}}',
  },
  {
    eventKey: EVENT_KEYS.RESULTS_AWAITING_APPROVAL,
    emailSubject: 'Results waiting for your approval: {{courseCode}}',
    emailBody: 'Dear {{firstName}},\n\nResults for {{courseCode}} {{courseTitle}} ({{semesterLabel}}) are waiting for your {{stage}}.\n\nReview them at {{portalUrl}}/academics/results\n\nAll Nations University',
    smsBody: 'ANU: Results for {{courseCode}} are waiting for your {{stage}}.',
    inAppTitle: 'Results waiting for your {{stage}}',
    inAppBody: '{{courseCode}} {{courseTitle}}, {{semesterLabel}}.',
  },
  {
    eventKey: EVENT_KEYS.RESULTS_RETURNED,
    emailSubject: 'Results returned for changes: {{courseCode}}',
    emailBody: 'Dear {{firstName}},\n\n{{actor}} returned the results for {{courseCode}} ({{semesterLabel}}) for changes.\n\nReason: {{note}}\n\nCorrect the marks and submit again at {{portalUrl}}/teaching\n\nAll Nations University',
    smsBody: 'ANU: Results for {{courseCode}} were returned for changes. Check your email.',
    inAppTitle: 'Results returned: {{courseCode}}',
    inAppBody: 'Reason: {{note}}',
  },
  {
    eventKey: EVENT_KEYS.ATTENDANCE_LOW,
    emailSubject: 'Your attendance in {{courseCode}} is below the minimum',
    emailBody: 'Dear {{firstName}},\n\nYour attendance in {{courseCode}} {{courseTitle}} is {{percent}}%. Students need at least {{minimum}}% to be eligible for the exam.\n\nAttend every remaining class. If you missed classes for a medical or other valid reason, take your documents to the Health Services or the Dean of Students so the absence can be excused.\n\nSee your attendance at {{portalUrl}}/attendance\n\nAll Nations University',
    smsBody: 'ANU: Your attendance in {{courseCode}} is {{percent}}%, below the {{minimum}}% needed to sit the exam. Please attend all remaining classes.',
    inAppTitle: 'Low attendance: {{courseCode}}',
    inAppBody: '{{percent}}% attended. The minimum for exams is {{minimum}}%.',
  },
  {
    eventKey: EVENT_KEYS.DEVOTION_FINAL,
    emailSubject: 'Your morning devotion score for {{semesterLabel}}',
    emailBody: 'Dear {{firstName}},\n\nYour morning devotion score for {{semesterLabel}} is {{score}} out of {{totalMarks}}.\n\nEarly: {{early}}. Late: {{late}}. Absent: {{absent}}. Excused: {{excused}}.\n\nSee the details at {{portalUrl}}/devotion\n\nChaplaincy\nAll Nations University',
    smsBody: 'ANU: Your morning devotion score for {{semesterLabel}} is {{score}} out of {{totalMarks}}.',
    inAppTitle: 'Devotion score: {{score}} / {{totalMarks}}',
    inAppBody: '{{semesterLabel}}. Early {{early}}, late {{late}}, absent {{absent}}.',
  },
  {
    eventKey: EVENT_KEYS.PARTNER_ACCOUNT_CREATED,
    emailSubject: 'Your All Nations University partner account',
    emailBody: 'Dear {{firstName}},\n\nAn account has been created for you on the All Nations University platform so you can list your hostel for students.\n\nSign-in email: {{email}}\n\nChoose your password using this link. It works once and expires in {{expiresHours}} hours:\n{{setupUrl}}\n\nThen sign in at {{portalUrl}}/staff/login. You will set up an authenticator app on your phone the first time.\n\nHostel Office\nAll Nations University',
    smsBody: 'ANU: Your partner account is ready. Check {{email}} for the link to set your password.',
    inAppTitle: 'Welcome',
    inAppBody: 'Your partner account is set up.',
  },
  {
    eventKey: EVENT_KEYS.HOSTEL_OFFERED,
    emailSubject: 'Hostel offer: {{hostel}}, room {{room}}',
    emailBody: 'Dear {{firstName}},\n\nYou have been offered a bed in {{hostel}}, room {{room}} ({{roomType}}) for {{semesterLabel}}. Fees: {{price}} per semester.\n\nAccept or decline by {{acceptBy}} at {{portalUrl}}/accommodation. If you do not respond, the bed goes to the next student waiting.\n\nHostel Office\nAll Nations University',
    smsBody: 'ANU: You are offered {{hostel}} room {{room}} for {{semesterLabel}}. Accept or decline by {{acceptBy}} in the student portal.',
    inAppTitle: 'Hostel offer: {{hostel}} {{room}}',
    inAppBody: 'Accept or decline by {{acceptBy}}.',
  },
  {
    eventKey: EVENT_KEYS.HOSTEL_UNPLACED,
    emailSubject: 'Hostel application: on the waiting list',
    emailBody: 'Dear {{firstName}},\n\nWe could not offer you a bed in your chosen university hostels for {{semesterLabel}} this round. You remain on the waiting list and will be offered a bed if one becomes free.\n\nYou can also look at verified private hostels at {{portalUrl}}/accommodation\n\nHostel Office\nAll Nations University',
    smsBody: 'ANU: No university hostel bed this round for {{semesterLabel}}. You are on the waiting list. Verified private hostels are listed in the student portal.',
    inAppTitle: 'Hostel application: waiting list',
    inAppBody: 'You are on the waiting list for {{semesterLabel}}.',
  },
  {
    eventKey: EVENT_KEYS.HOSTEL_OFFER_EXPIRED,
    emailSubject: 'Your hostel offer has expired',
    emailBody: 'Dear {{firstName}},\n\nYour offer of {{hostel}} room {{room}} expired because it was not accepted by {{acceptBy}}. The bed has gone to the next student waiting. Contact the Hostel Office if you still need accommodation.\n\nAll Nations University',
    smsBody: 'ANU: Your offer of {{hostel}} room {{room}} expired. Contact the Hostel Office if you still need a bed.',
    inAppTitle: 'Hostel offer expired',
    inAppBody: '{{hostel}} room {{room}} was not accepted in time.',
  },
  {
    eventKey: EVENT_KEYS.HOSTEL_ALLOCATION_CHANGED,
    emailSubject: 'Your hostel room has changed',
    emailBody: 'Dear {{firstName}},\n\n{{change}}\n\nSee the details at {{portalUrl}}/accommodation or contact the Hostel Office.\n\nAll Nations University',
    smsBody: 'ANU: {{change}}',
    inAppTitle: 'Hostel room changed',
    inAppBody: '{{change}}',
  },
  {
    eventKey: EVENT_KEYS.PRIVATE_BOOKING_REQUESTED,
    emailSubject: 'New booking request: {{hostel}}',
    emailBody: 'Dear {{firstName}},\n\n{{student}} has asked for a bed in {{roomType}} at {{hostel}} for {{semesterLabel}}.\n{{messageLine}}\n\nAccept or decline at {{portalUrl}}/my-hostel\n\nAll Nations University',
    smsBody: 'ANU: New booking request for {{hostel}}. Sign in to accept or decline.',
    inAppTitle: 'New booking request',
    inAppBody: '{{student}}: {{roomType}}.',
  },
  {
    eventKey: EVENT_KEYS.PRIVATE_BOOKING_RESPONDED,
    emailSubject: 'Booking {{decision}}: {{hostel}}',
    emailBody: 'Dear {{firstName}},\n\nYour request for {{roomType}} at {{hostel}} has been {{decision}}.\n{{noteLine}}\n{{nextStep}}\n\nAll Nations University',
    smsBody: 'ANU: Your booking at {{hostel}} was {{decision}}. {{smsNext}}',
    inAppTitle: 'Booking {{decision}}: {{hostel}}',
    inAppBody: '{{roomType}}. {{noteLine}}',
  },
  {
    eventKey: EVENT_KEYS.PRIVATE_BOOKING_CANCELLED,
    emailSubject: 'Booking cancelled: {{hostel}}',
    emailBody: 'Dear {{firstName}},\n\n{{student}} cancelled their booking for {{roomType}} at {{hostel}}. The bed is available again.\n\nAll Nations University',
    smsBody: 'ANU: A student cancelled a booking at {{hostel}}. The bed is available again.',
    inAppTitle: 'Booking cancelled',
    inAppBody: '{{student}}, {{roomType}}.',
  },
  {
    eventKey: EVENT_KEYS.HOSTEL_VERIFICATION,
    emailSubject: '{{hostel}}: {{outcome}}',
    emailBody: 'Dear {{firstName}},\n\nThe Hostel Office has reviewed {{hostel}}: {{outcome}}.\n{{noteLine}}\n\nManage your listing at {{portalUrl}}/my-hostel\n\nAll Nations University',
    smsBody: 'ANU: {{hostel}}: {{outcome}}. Check your email for details.',
    inAppTitle: '{{hostel}}: {{outcome}}',
    inAppBody: '{{noteLine}}',
  },
  {
    eventKey: EVENT_KEYS.LIBRARY_DUE_SOON,
    emailSubject: 'Library book due {{due}}',
    emailBody: 'Dear {{firstName}},\n\n"{{title}}" is due back on {{due}}. Renew it at {{portalUrl}}/library if you need it longer, or return it to the library desk.\n\nLibrary\nAll Nations University',
    smsBody: 'ANU Library: "{{shortTitle}}" is due {{due}}. Renew in the portal or return it.',
    inAppTitle: 'Book due {{due}}',
    inAppBody: '{{title}}',
  },
  {
    eventKey: EVENT_KEYS.LIBRARY_OVERDUE,
    emailSubject: 'Overdue library book: {{title}}',
    emailBody: 'Dear {{firstName}},\n\n"{{title}}" was due on {{due}} and is {{days}} days overdue.{{fineLine}}\n\nPlease return it to the library desk as soon as possible. You cannot borrow more books while it is overdue.\n\nLibrary\nAll Nations University',
    smsBody: 'ANU Library: "{{shortTitle}}" is {{days}} days overdue. Please return it.{{smsFine}}',
    inAppTitle: 'Overdue: {{shortTitle}}',
    inAppBody: '{{days}} days overdue.{{fineLine}}',
  },
  {
    eventKey: EVENT_KEYS.LIBRARY_HOLD_READY,
    emailSubject: 'Your reserved book is ready: {{title}}',
    emailBody: 'Dear {{firstName}},\n\n"{{title}}" is waiting for you at the library desk. Collect it by {{until}}, after which it goes to the next person waiting.\n\nLibrary\nAll Nations University',
    smsBody: 'ANU Library: "{{shortTitle}}" is ready at the desk. Collect by {{until}}.',
    inAppTitle: 'Reserved book ready',
    inAppBody: '{{title}}. Collect by {{until}}.',
  },
  {
    eventKey: EVENT_KEYS.LIBRARY_HOLD_EXPIRED,
    emailSubject: 'Reserved book not collected: {{title}}',
    emailBody: 'Dear {{firstName}},\n\n"{{title}}" was kept for you until {{until}} but was not collected, so it has gone to the next person. You can reserve it again at {{portalUrl}}/library\n\nLibrary\nAll Nations University',
    smsBody: 'ANU Library: "{{shortTitle}}" was not collected in time and has gone to the next person.',
    inAppTitle: 'Reservation expired',
    inAppBody: '{{title}}',
  },
  {
    eventKey: EVENT_KEYS.LIBRARY_FINE,
    emailSubject: 'Library fine: {{amount}}',
    emailBody: 'Dear {{firstName}},\n\nA library fine of {{amount}} has been charged: {{reason}}.\n\nYou now owe {{owed}} in total. Pay at the library desk. You cannot borrow while you owe {{blockAt}} or more.\n\nLibrary\nAll Nations University',
    smsBody: 'ANU Library: Fine of {{amount}} charged ({{reasonShort}}). You owe {{owed}}. Pay at the library desk.',
    inAppTitle: 'Library fine: {{amount}}',
    inAppBody: '{{reason}}. You owe {{owed}}.',
  },
  {
    eventKey: EVENT_KEYS.FOOD_ORDER_NEW,
    emailSubject: 'New order #{{number}}',
    emailBody: 'New order #{{number}} from {{customer}}: {{summary}}. {{fulfilment}}. Total {{total}} ({{payment}}).\n\nOpen your orders at {{portalUrl}}/vendor',
    smsBody: 'ANU Food: New order #{{number}}, {{total}}. Open your orders board.',
    inAppTitle: 'New order #{{number}}',
    inAppBody: '{{summary}}. {{fulfilment}}.',
  },
  {
    eventKey: EVENT_KEYS.FOOD_ORDER_UPDATE,
    emailSubject: 'Order #{{number}} from {{vendor}}: {{headline}}',
    emailBody: 'Dear {{firstName}},\n\nYour order #{{number}} from {{vendor}}: {{headline}}.\n{{detail}}\n\nTrack it at {{portalUrl}}/food/orders/{{orderId}}\n\nAll Nations University',
    smsBody: 'ANU Food: Order #{{number}} from {{vendor}}: {{headline}}. {{smsDetail}}',
    inAppTitle: 'Order #{{number}}: {{headline}}',
    inAppBody: '{{detail}}',
  },
  {
    eventKey: EVENT_KEYS.VENDOR_REVIEW,
    emailSubject: '{{vendor}}: {{outcome}}',
    emailBody: 'Dear {{firstName}},\n\n{{vendor}} has been {{outcome}} on the ANU food marketplace.\n{{noteLine}}\n\nManage your menu and orders at {{portalUrl}}/vendor\n\nAll Nations University',
    smsBody: 'ANU Food: {{vendor}} has been {{outcome}}. Check your email for details.',
    inAppTitle: '{{vendor}}: {{outcome}}',
    inAppBody: '{{noteLine}}',
  },
  {
    eventKey: EVENT_KEYS.RESULTS_PUBLISHED,
    emailSubject: 'Results published: {{courseCode}}',
    emailBody: 'Dear {{firstName}},\n\nResults for {{courseCode}} ({{semesterLabel}}) are now available on the student portal: {{portalUrl}}/results\n\nAll Nations University',
    smsBody: 'ANU: Results for {{courseCode}} ({{semesterLabel}}) are available. Sign in to the student portal to view them.',
    inAppTitle: 'Results published',
    inAppBody: 'Results for {{courseCode}} ({{semesterLabel}}) are available.',
  },
  {
    eventKey: EVENT_KEYS.INTERNALS_UPDATED,
    emailSubject: 'Internal marks updated: {{courseCode}}',
    emailBody: 'Dear {{firstName}},\n\nYour internal marks for {{courseCode}} ({{assessmentName}}) have been updated. View them at {{portalUrl}}/results\n\nAll Nations University',
    smsBody: 'ANU: Internal marks for {{courseCode}} ({{assessmentName}}) were updated. Sign in to view.',
    inAppTitle: 'Internal marks updated',
    inAppBody: '{{courseCode}}: {{assessmentName}} marks were updated.',
  },
  {
    eventKey: EVENT_KEYS.EXAM_TIMETABLE_PUBLISHED,
    emailSubject: 'Exam timetable {{action}}: {{semesterLabel}}',
    emailBody: 'Dear {{firstName}},\n\nThe exam timetable for {{semesterLabel}} has been {{action}}. {{changeSummary}}\n\nView your papers at {{portalUrl}}/exams\n\nAll Nations University',
    smsBody: 'ANU: The exam timetable for {{semesterLabel}} has been {{action}}. Sign in to view it.',
    inAppTitle: 'Exam timetable {{action}}',
    inAppBody: 'The {{semesterLabel}} exam timetable has been {{action}}.',
  },
  {
    eventKey: EVENT_KEYS.EXAM_ELIGIBILITY_PUBLISHED,
    emailSubject: 'Exam eligibility: {{semesterLabel}}',
    emailBody: 'Dear {{firstName}},\n\nExam eligibility status for {{semesterLabel}}: {{status}}.\n{{reasonLine}}\n\nDetails and your exam entry slip: {{portalUrl}}/exams\n\nAll Nations University',
    smsBody: 'ANU: Your exam eligibility for {{semesterLabel}}: {{status}}. {{smsReason}}',
    inAppTitle: 'Exam eligibility: {{status}}',
    inAppBody: '{{semesterLabel}}: {{status}}. {{reasonLine}}',
  },
  {
    eventKey: EVENT_KEYS.ACCOUNT_LOCKED,
    emailSubject: 'Your account was temporarily locked',
    emailBody: 'Your account was locked for 15 minutes after 5 failed sign-in attempts at {{time}}. If this was not you, contact ICT support.',
    smsBody: 'ANU: Your account was locked for 15 minutes after 5 failed sign-in attempts. If this was not you, contact ICT.',
    inAppTitle: 'Account temporarily locked',
    inAppBody: 'Locked after 5 failed sign-in attempts at {{time}}.',
  },
  {
    eventKey: EVENT_KEYS.PASSWORD_RESET_CODE,
    emailSubject: 'Your password reset code',
    emailBody: 'Your password reset code is {{code}}. It expires in 10 minutes. If you did not ask for this, ignore this message.',
    smsBody: 'ANU: Your password reset code is {{code}}. It expires in 10 minutes.',
    inAppTitle: 'Password reset requested',
    inAppBody: 'A password reset code was sent.',
  },
  {
    eventKey: EVENT_KEYS.PASSWORD_CHANGED,
    emailSubject: 'Your password was changed',
    emailBody: 'Your password was changed at {{time}}. If this was not you, contact ICT support immediately.',
    smsBody: 'ANU: Your password was changed at {{time}}. If this was not you, contact ICT.',
    inAppTitle: 'Password changed',
    inAppBody: 'Your password was changed at {{time}}.',
  },
  {
    eventKey: EVENT_KEYS.DEVELOPER_ACCESS_CHANGED,
    emailSubject: 'Developer access {{state}}',
    emailBody: 'Developer access on your account was {{state}} by {{actor}} at {{time}}. Reason: {{reason}}',
    smsBody: 'ANU: Developer access on your account was {{state}}.',
    inAppTitle: 'Developer access {{state}}',
    inAppBody: 'Reason: {{reason}}',
  },
];

export function render(template: string, vars: Record<string, string | number | undefined>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k: string) => String(vars[k] ?? '')).trim();
}
