/** A link that downloads a PDF generated by the server. */
export function PdfLink({ api, label = 'Download PDF' }: { api: string; label?: string }) {
  return <a href={`/api/v1${api}`} className="text-sm text-primary hover:underline print:hidden" download>{label}</a>;
}
