const ACTION_LABELS: Record<string, string> = {
  'auth.login.success': 'Signed in',
  'auth.login.failed': 'Failed sign-in attempt',
  'auth.login.password_ok': 'Password accepted, awaiting verification',
  'auth.mfa.failed': 'Failed verification code',
  'auth.mfa.enrolled': 'Set up two-step verification',
  'auth.logout': 'Signed out',
  'auth.account.locked': 'Account locked after failed attempts',
  'auth.role.switched': 'Switched active role',
  'auth.step_up.success': 'Confirmed identity for a sensitive action',
  'auth.step_up.failed': 'Failed identity confirmation',
  'auth.password.changed': 'Changed password',
  'auth.password.change_failed': 'Failed password change',
  'auth.password.reset_requested': 'Requested password reset',
  'auth.password.reset_throttled': 'Too many reset codes requested (ignored)',
  'auth.password.reset': 'Reset password',
  'auth.session.revoked': 'Signed out another device',
  'auth.refresh.reuse_detected': 'Session ended: token reuse detected',
  'student.registered': 'Registered a student',
  'staff.created': 'Created a staff account',
  'fees.rules_changed': 'Changed fee rules (clearance percentage or payment minimums)',
  'fees.item_created': 'Added a fee item',
  'fees.item_updated': 'Changed a fee item',
  'registry.school_created': 'Added a school',
  'registry.school_updated': 'Changed a school',
  'registry.department_created': 'Added a department',
  'registry.department_updated': 'Changed a department',
  'registry.department_deleted': 'Removed a department',
  'registry.programme_created': 'Added a programme',
  'registry.programme_updated': 'Changed a programme',
  'registry.programme_deleted': 'Removed a programme',
  'registry.type_created': 'Added a programme type',
  'registry.type_updated': 'Changed a programme type or index format',
  'fees.schedule_created': 'Added a fee schedule',
  'fees.schedule_updated': 'Changed a fee schedule',
  'fees.schedule_deleted': 'Removed a fee schedule',
  'fees.schedules_copied': 'Copied fee schedules from another semester',
  'fees.bills_issued': 'Issued fee bills',
  'fees.payment_recorded': 'Recorded a fee payment',
  'fees.payment_reversed': 'Reversed a fee payment',
  'fees.waiver_added': 'Added a fee waiver or scholarship',
  'fees.charge_added': 'Added an extra fee charge',
  'fees.auto_cleared': 'Fee-cleared automatically by the payment rule',
  'fees.auto_uncleared': 'Fee clearance withdrawn by the payment rule',
  'dues.association_created': 'Added a departmental association',
  'dues.association_updated': 'Changed a departmental association',
  'dues.officer_appointed': 'Recorded an elected association officer',
  'dues.officer_ended': 'Ended an association officer term',
  'dues.levy_created': 'Set departmental dues',
  'dues.levy_closed': 'Closed departmental dues',
  'dues.levy_reopened': 'Reopened departmental dues',
  'dues.cash_recorded': 'Recorded a cash dues payment',
  'dues.receipt_voided': 'Cancelled a dues receipt',
  'dues.payout_recorded': 'Recorded a dues payout to an association',
  'students.status_changed': 'Suspended, deactivated or reactivated a student account',
  'registrations.advisor_assigned': 'Assigned students to an academic advisor',
  'registrations.advisor_removed': "Removed students' academic advisor",
  'library.fine_paid_online': 'Paid a library fine online',
  'fees.hall_fee_charged': 'Hall fees charged or adjusted on a fee bill',
  'fees.hall_fee_skipped': 'Hall fee not added (bill in US dollars)',
  'uploads.menu_photo_set': 'Changed a dish photo',
  'uploads.hostel_photos_set': 'Changed hostel photos',
  'results.amendment_requested': 'Requested a result amendment',
  'results.amendment_approved': 'Approved a result amendment',
  'results.amendment_applied': 'Applied a result amendment',
  'results.amendment_rejected': 'Rejected a result amendment',
  'exams.seats_allocated': 'Numbered exam seats',
  'exams.invigilators_notified': 'Sent invigilators their duties',
  'exams.register_closed': 'Closed an exam attendance register',
  'fees.rate_added': 'Added an exchange rate',
  'fees.rate_deleted': 'Removed an exchange rate',
  'marketplace.order_marked_paid': 'Marked a food order paid (cash or MoMo)',
  'exams.dues_marker_on': 'Turned on the unpaid-dues marker on exam registers',
  'exams.dues_marker_off': 'Turned off the unpaid-dues marker on exam registers',
  'registry.devotion_rule_changed': 'Changed whether devotion counts in course totals',
  'accommodation.hostel_fee_recorded': 'Recorded a hostel fee payment',
  'accommodation.hostel_fee_reversed': 'Reversed a hostel fee payment',
  'accommodation.owner_payout_recorded': 'Recorded a payout to a hostel owner',
  'accommodation.form_added': 'Added a hostel form',
  'accommodation.form_submitted': 'Sent a signed hostel form',
  'accommodation.form_accepted': 'Accepted a signed hostel form',
  'accommodation.form_returned': 'Returned a signed hostel form',
  'accommodation.checked_in': 'Checked a student in to a hostel',
  'accommodation.checked_out': 'Checked a student out of a hostel',
  'attendance.excuse_requested': 'Asked to be excused',
  'attendance.excuse_request_approved': "Approved a student's excuse request",
  'attendance.excuse_request_declined': "Declined a student's excuse request",
  'devotion.exemption_granted': 'Exempted a student from morning devotion',
  'devotion.exemption_revoked': 'Removed a devotion exemption',
  'registration.reopened': 'Reopened an approved registration',
  'documents.opened': 'Opened a private document',
  'library.clearance_issued': 'Issued a library clearance certificate',
  'library.ebook_set': 'Set an e-book for a title',
  'library.ill_requested': 'Requested an inter-library loan',
  'library.ill_updated': 'Updated an inter-library loan',
  'library.reading_list_saved': 'Saved a course reading list',
  'marketplace.meal_plan_bought': 'Bought a meal plan',
  'marketplace.meal_plan_created': 'Added a meal plan',
  'marketplace.meal_plan_updated': 'Changed a meal plan',
  'marketplace.rating_hidden': 'Hid a customer comment',
  'marketplace.rating_shown': 'Showed a customer comment again',
  'accommodation.owner_payout_details': 'Changed hostel payout details',
  'payments.transfer_started': 'Sent a payout through Paystack',
  'payments.transfer_succeeded': 'Paystack payout succeeded',
  'payments.transfer_failed': 'Paystack payout failed',
  'employment.timesheet_approved': 'Approved a timesheet',
  'employment.timesheet_returned': 'Returned a timesheet',
  'employment.timesheet_paid': 'Paid a timesheet',
  'imports.finished': 'Imported records from the previous system',
  'imports.setup_links_sent': 'Sent set-up emails to imported accounts',
  'accommodation.complaint_filed': 'Complained about a private hostel',
  'accommodation.complaint_handled': 'Handled a hostel complaint',
  'accommodation.complaint_answered': 'Responded to a hostel complaint',
  'fees.instalments_set': 'Set the instalment plan',
  'fees.late_charges_added': 'Added late payment charges',
  'fees.statement_imported': 'Recorded payments from a bank statement',
  'security.retention_changed': 'Changed records retention',
  'dues.patron_set': "Named an association's patron",
  'staff.status_changed': 'Suspended, deactivated or reactivated an account',
  'staff.roles.updated': 'Changed a staff member\'s roles',
  'account.setup_link.sent': 'Sent an account setup link',
  'account.setup.completed': 'Set up account password',
  'semester.updated': 'Changed semester settings',
  'offering.created': 'Added a course to a semester',
  'offering.bulk_created': 'Added a department\'s courses to a semester',
  'offering.capacity_changed': 'Changed a course seat limit',
  'offering.removed': 'Removed a course from a semester',
  'offering.lecturers_set': 'Assigned lecturers to a course',
  'teaching.roster_viewed': 'Viewed a class list',
  'registration.saved': 'Saved course registration',
  'registration.submitted': 'Submitted course registration',
  'registration.withdrawn': 'Withdrew course registration',
  'registration.approved': 'Approved a course registration',
  'registration.rejected': 'Returned a course registration for changes',
  'grading.scale_saved': 'Saved a new grading scale',
  'marks.scheme_saved': 'Set up course assessments',
  'marks.saved': 'Entered marks',
  'marks.shared': 'Shared continuous assessment with students',
  'results.submitted': 'Submitted results for approval',
  'results.approved_department': 'Approved results as Head of Department',
  'results.approved_school': 'Approved results as Dean',
  'results.published': 'Published results',
  'results.returned': 'Returned results to the lecturer',
  'exams.venue_created': 'Added an exam venue',
  'exams.venue_updated': 'Changed an exam venue',
  'exams.paper_scheduled': 'Scheduled an exam paper',
  'exams.paper_removed': 'Removed an exam paper',
  'exams.timetable_published': 'Published the exam timetable',
  'exams.timetable_republished': 'Published exam timetable changes',
  'exams.eligibility_policy_changed': 'Changed exam eligibility rules',
  'exams.eligibility_generated': 'Generated exam eligibility',
  'exams.eligibility_overridden': 'Overrode an exam eligibility decision',
  'exams.eligibility_override_removed': 'Removed an exam eligibility override',
  'exams.eligibility_published': 'Published exam eligibility',
  'exams.hold_placed': 'Placed an exam hold',
  'exams.hold_lifted': 'Lifted an exam hold',
  'finance.clearance_granted': 'Cleared students for exams',
  'finance.clearance_revoked': 'Withdrew exam fee clearance',
  'attendance.policy_changed': 'Changed attendance rules',
  'attendance.sessions_created': 'Added classes',
  'attendance.session_updated': 'Changed a class time',
  'attendance.session_cancelled': 'Cancelled a class',
  'attendance.register_saved': 'Saved a class register',
  'attendance.checkin_opened': 'Opened class check-in',
  'attendance.checkin_closed': 'Closed class check-in',
  'attendance.checked_in': 'Checked in to a class',
  'attendance.checkin_failed': 'Entered a wrong check-in code',
  'attendance.excuse_recorded': 'Recorded an excused absence',
  'attendance.excuse_revoked': 'Withdrew an excused absence',
  'devotion.policy_changed': 'Changed devotion rules',
  'devotion.services_generated': 'Scheduled devotion services',
  'devotion.service_added': 'Added a special devotion service',
  'devotion.service_cancelled': 'Cancelled a devotion service',
  'devotion.checked_in': 'Checked in to morning devotion',
  'devotion.checkin_failed': 'Entered a wrong devotion code',
  'devotion.record_corrected': 'Corrected a devotion record',
  'devotion.service_closed': 'Closed a devotion service',
  'devotion.scores_finalised': 'Finalised devotion scores',
  'hostels.hostel_created': 'Added a university hostel',
  'hostels.hostel_updated': 'Changed a university hostel',
  'hostels.rooms_added': 'Added hostel rooms',
  'hostels.room_updated': 'Changed a hostel room',
  'hostels.round_saved': 'Set the hostel application window',
  'hostels.special_needs_approved': 'Confirmed a special accommodation need',
  'hostels.special_needs_declined': 'Removed special accommodation priority',
  'hostels.allocation_run': 'Ran hostel allocation',
  'hostels.allocation_published': 'Published hostel offers',
  'hostels.manual_allocation': 'Placed a student in a hostel by hand',
  'hostels.allocation_moved': 'Moved a student to another room',
  'hostels.allocation_cancelled': 'Cancelled a hostel place',
  'hostels.private_verified': 'Reviewed a private hostel',
  'hostels.owner_created': 'Created a hostel owner account',
  'hostels.private_listed': 'Listed a private hostel',
  'hostels.private_updated': 'Changed a private hostel',
  'hostels.room_type_added': 'Added a private room type',
  'hostels.room_type_updated': 'Changed a private room type',
  'hostels.booking_accepted': 'Accepted a hostel booking',
  'hostels.booking_declined': 'Declined a hostel booking',
  'accommodation.applied': 'Applied for a university hostel',
  'accommodation.application_updated': 'Changed a hostel application',
  'accommodation.application_withdrawn': 'Withdrew a hostel application',
  'accommodation.offer_accepted': 'Accepted a hostel offer',
  'accommodation.offer_declined': 'Declined a hostel offer',
  'accommodation.private_requested': 'Asked a private hostel for a bed',
  'accommodation.private_cancelled': 'Cancelled a private hostel booking',
  'accommodation.residence_declared': 'Said where they live',
  'library.policy_changed': 'Changed library rules',
  'library.title_added': 'Added a title to the catalogue',
  'library.title_updated': 'Changed a catalogue title',
  'library.copies_added': 'Added copies of a title',
  'library.copy_updated': 'Changed a library copy',
  'library.issued': 'Issued a library book',
  'library.returned': 'Returned a library book',
  'library.renewed': 'Renewed a library book',
  'library.renewed_at_desk': 'Renewed a library book at the desk',
  'library.declared_lost': 'Marked a library book as lost',
  'library.reserved': 'Reserved a library book',
  'library.reservation_cancelled': 'Cancelled a library reservation',
  'library.fine_paid': 'Took a library fine payment',
  'library.fine_waived': 'Waived a library fine',
  'marketplace.settings_changed': 'Changed food marketplace settings',
  'marketplace.vendor_created': 'Added a food vendor',
  'marketplace.vendor_reviewed': 'Approved, suspended or rejected a vendor',
  'marketplace.vendor_profile_updated': 'Changed shop settings',
  'marketplace.vendor_paused': 'Paused new orders',
  'marketplace.vendor_resumed': 'Resumed taking orders',
  'marketplace.menu_item_added': 'Added a dish',
  'marketplace.menu_item_updated': 'Changed a dish',
  'marketplace.payout_recorded': 'Recorded a vendor payout',
  'marketplace.order_placed': 'Placed a food order',
  'marketplace.order_accepted': 'Accepted a food order',
  'marketplace.order_rejected': 'Declined a food order',
  'marketplace.order_ready': 'Marked a food order ready',
  'marketplace.order_out_for_delivery': 'Sent a food order for delivery',
  'marketplace.order_completed': 'Handed over a food order',
  'marketplace.order_cancelled': 'Cancelled a food order',
  'employment.rules_changed': 'Changed employment rules',
  'employment.job_created': 'Posted a campus job',
  'employment.job_updated': 'Changed a campus job',
  'employment.job_status': 'Opened or closed a campus job',
  'employment.applied': 'Applied for a campus job',
  'employment.withdrawn': 'Withdrew a job application',
  'employment.application_shortlisted': 'Shortlisted a job applicant',
  'employment.application_hired': 'Hired a student',
  'employment.application_rejected': 'Turned down a job applicant',
  'employment.application_ended': "Ended a student's job",
  'employment.dispatcher_applied': 'Applied to be a dispatcher',
  'employment.dispatcher_payout_changed': 'Changed dispatcher payout details',
  'employment.dispatcher_active': 'Approved a dispatcher or lifted a suspension',
  'employment.dispatcher_rejected': 'Turned down a dispatcher',
  'employment.dispatcher_suspended': 'Suspended a dispatcher',
  'employment.dispatcher_ended': "Ended a dispatcher's role",
  'employment.dispatcher_auto_suspended': 'Dispatcher suspended automatically (rules no longer met)',
  'dispatch.online': 'Went online for deliveries',
  'dispatch.offline': 'Went offline for deliveries',
  'dispatch.taken': 'Took a delivery',
  'dispatch.released': 'Handed a delivery back',
  'dispatch.problem': 'Reported a delivery problem',
  'dispatch.payout_recorded': 'Recorded a dispatcher payout',
  'payments.succeeded': 'Payment succeeded',
  'payments.failed': 'Payment failed',
  'payments.mismatch': 'Payment amount did not match',
  'payments.webhook_rejected': 'Rejected a payment notice with a bad signature',
  'payments.refund_started': 'Started a refund',
  'payments.refund_failed': 'Refund failed',
  'student.viewed': 'Viewed a student record',
  'developer.access.enabled': 'Enabled Developer access',
  'developer.access.disabled': 'Disabled Developer access',
  'developer.access.expired': 'Developer access expired',
  'audit.export.own': 'Exported own activity',
  'audit.export.all': 'Exported activity log',
  'notification.delivery.resend': 'Resent a notification',
};

export function actionLabel(action: string) {
  return ACTION_LABELS[action] ?? action;
}

export const MODULE_OPTIONS = [
  { value: 'auth', label: 'Sign-in and security' },
  { value: 'students', label: 'Students' },
  { value: 'staff', label: 'Staff' },
  { value: 'accounts', label: 'Account setup' },
  { value: 'academics', label: 'Semesters' },
  { value: 'teaching', label: 'Courses and teaching' },
  { value: 'registration', label: 'Course registration' },
  { value: 'results', label: 'Marks and results' },
  { value: 'exams', label: 'Examinations' },
  { value: 'attendance', label: 'Attendance' },
  { value: 'devotion', label: 'Morning devotion' },
  { value: 'accommodation', label: 'Accommodation' },
  { value: 'library', label: 'Library' },
  { value: 'marketplace', label: 'Food marketplace' },
  { value: 'payments', label: 'Payments' },
  { value: 'fees', label: 'Fees' },
  { value: 'registry', label: 'Registry' },
  { value: 'documents', label: 'Documents' },
  { value: 'imports', label: 'Imports' },
  { value: 'security', label: 'Security' },
  { value: 'registrations', label: 'Course registration' },
  { value: 'dues', label: 'Departmental dues' },
  { value: 'employment', label: 'Student employment' },
  { value: 'dispatch', label: 'Deliveries' },
  { value: 'rbac', label: 'Roles and access' },
  { value: 'audit', label: 'Activity log' },
  { value: 'notifications', label: 'Notifications' },
];
