import { ROLE_KEYS, RoleKey } from './roles';

export const LOG_GROUPS = {
  STUDENTS: 'STUDENTS',
  LECTURERS: 'LECTURERS',
  LIBRARIANS: 'LIBRARIANS',
  NON_TEACHING_STAFF: 'NON_TEACHING_STAFF',
  MANAGEMENT: 'MANAGEMENT',
  EXTERNAL_PARTNERS: 'EXTERNAL_PARTNERS',
  DEVELOPERS: 'DEVELOPERS',
  ADMINISTRATORS: 'ADMINISTRATORS',
} as const;

export type LogGroup = (typeof LOG_GROUPS)[keyof typeof LOG_GROUPS];

export const LOG_GROUP_LABELS: Record<LogGroup, string> = {
  STUDENTS: 'Students',
  LECTURERS: 'Lecturers and academic staff',
  LIBRARIANS: 'Library staff',
  NON_TEACHING_STAFF: 'Non-teaching staff',
  MANAGEMENT: 'University management',
  EXTERNAL_PARTNERS: 'External partners',
  DEVELOPERS: 'Developers',
  ADMINISTRATORS: 'Super Admins',
};

/** Which activity-log group an action falls under, based on the role the person was acting in. */
export const ROLE_LOG_GROUP: Record<RoleKey, LogGroup> = {
  [ROLE_KEYS.SUPER_ADMIN]: 'ADMINISTRATORS',
  [ROLE_KEYS.DEVELOPER]: 'DEVELOPERS',
  [ROLE_KEYS.VICE_CHANCELLOR]: 'MANAGEMENT',
  [ROLE_KEYS.PRO_VICE_CHANCELLOR]: 'MANAGEMENT',
  [ROLE_KEYS.DEAN]: 'LECTURERS',
  [ROLE_KEYS.HEAD_OF_DEPARTMENT]: 'LECTURERS',
  [ROLE_KEYS.PROGRAMME_COORDINATOR]: 'LECTURERS',
  [ROLE_KEYS.ACADEMIC_ADVISOR]: 'LECTURERS',
  [ROLE_KEYS.LECTURER]: 'LECTURERS',
  [ROLE_KEYS.TEACHING_ASSISTANT]: 'LECTURERS',
  [ROLE_KEYS.REGISTRAR]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.ADMISSIONS_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.EXAM_COORDINATOR]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.QA_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.DEAN_OF_STUDENTS]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.COUNSELLOR]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.CHAPLAINCY_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.HEALTH_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.CAREER_SERVICES_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.HOSTEL_MANAGER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.LIBRARIAN]: 'LIBRARIANS',
  [ROLE_KEYS.LIBRARY_ASSISTANT]: 'LIBRARIANS',
  [ROLE_KEYS.FINANCE_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.HR_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.ICT_SUPPORT]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.SECURITY_OFFICER]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.INTERNAL_AUDITOR]: 'NON_TEACHING_STAFF',
  [ROLE_KEYS.EXTERNAL_EXAMINER]: 'EXTERNAL_PARTNERS',
  [ROLE_KEYS.PRIVATE_HOSTEL_OWNER]: 'EXTERNAL_PARTNERS',
  [ROLE_KEYS.VENDOR]: 'EXTERNAL_PARTNERS',
  [ROLE_KEYS.STUDENT]: 'STUDENTS',
  [ROLE_KEYS.STUDENT_DISPATCHER]: 'STUDENTS',
  [ROLE_KEYS.ASSOCIATION_OFFICER]: 'STUDENTS',
};
